### ISSUE TITLE
DVC Dropdown Menu Inclusion

### ISSUE THREAD

**Issue by 0bsolescence** [PaloAltoNetworks/SplunkforPaloAltoNetworks#12]
Thanks for the awesome work! Is there any chance that you could add a dropdown menu to select what dvc you're seeing in addition to the vsys as well? Thanks!

**Comment by btorresgil** [comment]
Hello, can you describe further the need for the dvc field, and in which dashboards you'd like to see this field?

It is possible to add any field you want to the dashboards using the current fields as a reference.  The fields are created using macros so that it is easy to add new fields or modify existing ones.  If you'd like help creating your own custom dropdown filters, please open a question at https://answers.splunk.com/answers/ask.html?appid=491 and I'll be happy to dig into the details.

**Comment by btorresgil** [comment]
Bumping this issue.  Any feedback on the use case for dvc field and in which dashboards you'd like to see this field as a filter?

**Comment by btorresgil** [comment]
Closing this issue, no response.  Feel free to comment and I can re-open it.  Thanks!
