### ISSUE TITLE
Datamodel Issues

### ISSUE THREAD

**Issue by doksu** [PaloAltoNetworks/SplunkforPaloAltoNetworks#17]
Hi Brian,

I've had some issues using the app when ingesting 100GB+ of PAN events a day and after speaking with other Palo Alto customers it seems I'm not alone.

The first issue is the default acceleration time, however, I noticed it's now been changed from 'all time' to '1w'. That's really good, but also reckon third-party apps like this shouldn't **automatically** enable datamodel acceleration. It's a bit like having indexes.conf in Splunkbase apps, it's just not cool. :) What are your thoughts on perhaps changing this? The `pan_tstats` macro should also probably not have 'summariesonly=t'.

The biggest issue however is the size and number of datamodels. In large environments they're **huge** and they've resulted in heavy indexer load and instability in our environment on more than one occation.

Hope this is helpful feedback mate.

Thanks,
Doksu

**Comment by btorresgil** [comment]
Hi Doksu,

Thanks for your comments.  I'll address each one:

-  Third-party apps like this shouldn't automatically enable datamodel acceleration

Generally, I agree with you.  However, most vendor apps don't have to deal with the sheer volume of data that we have to in each dashboard.  The firewall can generate a dozen logs for each network flow in order to convey the detail and visibility it has into the flow.  So all the dashboards in the App have to use the accelerated summary index created by the datamodel because they would be unusably slow pulling raw logs from the index.  We work very closely with Splunk in the development of our App as they are a strategic partner of ours, and this course was a recommendation from their App development team.  In fact, many of the techniques used in our App come directly from Splunk as recommendations and best practices.

Your feedback here is still important, which is one of the reasons we split the App into an App and [Add-on](https://splunkbase.splunk.com/app/2757/) starting with App version 5.0.0.  If you don't need the datamodel and acceleration, then you can install only the [Add-on](https://splunkbase.splunk.com/app/2757/).  If you prefer to have the dashboards that are included in the App, then the App comes with the datamodel and acceleration necessary to make the dashboards work.

-  The pan_tstats macro should also probably not have 'summariesonly=t'.

You are welcome to remove 'summariesonly=t'.  That's why we put it in a macro, so you can easily enable and disable it globally.  However, you'll notice that if you disable it, your dashboards will take longer to come up because Splunk is pulling from both the accelerated and non-accelerated data.  Slower dashboards did not seem like a good default and tested poorly in customer feedback sessions.  So we left it as a customization you can make yourself.

-  Size and number of datamodels

Every environment is different, and a datamodel that works great and provides required detail in one environment might be overly verbose in another environment, or run slower in another with higher log volume.  What we've attempted to create in the App is a collection of good defaults.  But you are welcome to tune the datamodel to your needs.  You can change acceleration timeframes, change how dashboard data is pulled, remove extra fields from the datamodel that you don't need, etc.  The datamodel in the latest version of the App has been checked by several teams at Splunk including the datamodel PM's, and is the collection of all the best practices and optimizations we could get.  Even after that, it is still not a one-size-fits-all, but it's the closest we feel we could get.

It sounds like what is really needed is a guide that instructs administrators in all the App customizations that can be made to taylor the App/Add-on to your environment, and the benefits and drawbacks of each customization.  Something like a post-install customization guide.  I've heard this feedback a couple times now, so I'm starting to work on this part of the App's manual.  Let me know in the comments here if this would be helpful, and any feedback I should incorporate while writing this documentation.

Thanks for taking the time to provide feedback!
 -Brian

**Comment by doksu** [comment]
Thanks Brian, I agree on all counts and can appreciate the challenge of making apps the work well in different Splunk environments.

Here's something I've done in our environment that *might* be useful in the doco (assuming Splunk agrees with my suggestion):

    Create a filesystem on the indexers specifically for datamodel acceleration then override the default datamodel volume's path to use that filesystem and apply a volume size restriction so it can never overflow:

    [volume:_splunk_summaries]
    path = $SPLUNK_HOME/var/lib/splunk/summary
    maxVolumeDataSizeMB = 50000

Hope this helps. You'll have to try my app (https://splunkbase.splunk.com/app/2642/) and provide feedback so I can make it better! :)
