### ISSUE TITLE
ES - suggest changing signature field

### ISSUE THREAD

**Issue by niemesrw** [PaloAltoNetworks/SplunkforPaloAltoNetworks#39]
I'm a Splunk app for Enterprise Security user.  The Intrusion_Detection datamodel has a signature field that the app is currently assigning using an eval expression in props.conf.  It means the signature field looks like this typically "Vulnerability exploit detection(35364)"

My preference is to use the lookup table already supplied with the TA and assign signature from the field name threat:name populated from that lookup.  So my props entry is:

[pan:threat]
LOOKUP-pan_threat_id = threat_lookup threat_id OUTPUT "threat:category" "threat:cve" "threat:name" AS signature "threat:severity"

And the signatures look more like this (IMO more descriptive): "Microsoft Windows SMB Negotiate Request"

If you guys agree I'm happy to do the git pull, but didn't want to before someone had a chance to disagree with me.  There are obviously more ways to do this but I feel the lookup is most scalable.

**Comment by btorresgil** [comment]
Hello, thanks for opening this issue.

One concern with this approach is that threat id's (the number portion) can be reused.  So, you might end up with a situation where the signature field has the name of one signature and the threat:name field has a different threat name.  This is unlikely with recent events, but the further you look back at older logs, it is possible the id could be reused.  We're aware of this limitation and it will be solved in the future by always using unique threat id's.

Additionally, not everyone sets up the metadata sync feature to keep the threat lookup tables updated, so for some customer they could be out of sync with the firewall.

Due to those two reasons, I'm reluctant to use `threat:name` field over the `signature` field. I think `threat:name` should decorate the log fields, not replace them.  However, if you decide to implement it and want to share your code, I'd be happy to add it to the documentation as an alternative approach.  And both the concerns above will eventually be resolved, so we can re-evaluate in the future.

**Comment by btorresgil** [comment]
Closing out this issue, but if you have further concerns on this please feel free to comment.
