### ISSUE TITLE
Traffic | Web Activity Report DM constraints

### ISSUE THREAD

**Issue by Kevin-Manson** [PaloAltoNetworks/SplunkforPaloAltoNetworks#41]
The datamodel constraints for Log.url are incorrect. So the web activity report and Content Dashboard do not work.

Current 3.7.1:
`eventtype="pan_threat" log_subtype="url"`

The correct constraints are:
`eventtype="pan_url" log_subtype="url"`

**Comment by btorresgil** [comment]
Hi Kevin, thanks for opening this issue.

The `log_subtype` constraint is built into the pan_url eventtype, so if the datamodel is modified to use `eventtype="pan_url"` then it can leave off the `log_subtype="url"` part.

However, the datamodel should be able to use either of the following constraints with equal performance impact:

    eventtype="pan_threat" log_subtype="url"
    
    - or -
    
    eventtype="pan_url"

These constrains are equal as far as I know.  Is there a particular reason you suggest using the "pan_url" eventtype, instead of adding the log_subtype constraint to the "pan_threat" eventtype?

**Comment by btorresgil** [comment]
Hi, just checking in on this issue, let me know if you still have concerns on this, otherwise we'll close it out.
